### ISSUE TITLE
Contract Role Sign Convention utility function missing a value.

### ISSUE THREAD

**Issue by brunoffranca** [actusfrf/actus-techspecs#13]
The table for the Contract Role Sign Convention utility function (https://github.com/actusfrf/actus-techspecs/blob/master/actus-techspecs.tex#L545) only lists 7 values (RPA, RPL, LG, ST, RFL, PFL, BUY, SEL, COL, GUA, OBL). However, the definition for the Contract Role attribute (https://github.com/actusfrf/actus-dictionary/blob/master/actus-dictionary-terms.json#L226) also lists the value "CNO".
The Contract Role Sign convention for the value "CNO" needs to be added to the table.

**Comment by nbundi** [comment]
value added, but need to implement effect on payoff for which I will open a separate issue. thanks
