### ISSUE TITLE
Typo in the Annuity amount function definition

### ISSUE THREAD

**Issue by brunoffranca** [actusfrf/actus-techspecs#14]
In the section for the Annuity amount function it reads "A(,c,o,m,p)utes", it should read "A computes" or "A(s, T, n, a, r) computes".
The problem seems to be in the use of the command $\ann$ (https://github.com/actusfrf/actus-techspecs/blob/master/actus-techspecs.tex#L582). Changing it to $A$ or $\ann{s}{T}{n}{a}{r}$ should solve the issue.

**Comment by nbundi** [comment]
thank you @brunoffranca, fixed this
