### ISSUE TITLE
Typo in PAM contract.

### ISSUE THREAD

**Issue by brunoffranca** [actusfrf/actus-techspecs#17]
Refers to variable FAC (https://github.com/actusfrf/actus-techspecs/blob/master/actus-techspecs.tex#L947), it should be FEAC according to the new nomenclature.

**Comment by brunoffranca** [comment]
Actually, that same typo appears through the rest of the PAM contract definition.

**Comment by nbundi** [comment]
fixed with c2a9633f4cc9979ad144069e3fe00fa6cba609cf
